In [1]:
from pytagi.nn import Linear, OutputUpdater, ReLU, Sequential, EvenExp
import numpy as np
import torch

In [2]:
class TAGI_Net():
    def __init__(self, n_observations, n_actions):
        super(TAGI_Net, self).__init__()
        self.net = Sequential(
                    Linear(n_observations, 1000),
                    ReLU(),
                    Linear(1000, 1000),
                    ReLU(),
                    Linear(1000, n_actions),
                    # EvenExp()
                    )
        self.n_actions = n_actions
        self.n_observations = n_observations
    def forward(self, mu_x, var_x):
        return self.net.forward(mu_x, var_x)

In [3]:
test_net = TAGI_Net(1, 4)
# test_net.net.eval()
for itr in range(100):
    for state in range(16):
        state = state
        state_np = np.array([state], dtype=np.float32)
        ma, Sa = test_net.net(state_np)
        print(state)
        print(ma)
        print(Sa)
        print('=====================')

0
[-0.59637576 -0.16779573  0.16565125 -0.41489258]
[1.7529514 1.7275032 1.682883  1.6593474]
1
[-0.6540697  -0.6835451  -0.10135586 -0.7718113 ]
[3.651388  3.7742789 3.5688064 3.6042087]
2
[-0.70443654 -0.76094556 -0.25405586 -0.58398455]
[ 9.286512 10.0059    9.070627  9.04651 ]
3
[-0.5082863  -1.0777049  -0.58798647 -0.33082992]
[18.52917  19.687956 18.098974 18.037638]
4
[-0.45167077 -1.4840765  -0.92131186 -0.14677995]
[32.07671  34.285984 31.576254 31.448584]
5
[-0.39777    -1.8649567  -1.2999322   0.02091085]
[49.71394  53.306503 48.68304  48.543888]
6
[-0.3939716  -2.213275   -1.6746491   0.16680317]
[71.19972 75.88085 69.6718  69.70921]
7
[-0.43705118 -2.5483685  -2.0633543   0.2942355 ]
[ 97.11897 103.7642   95.15997  95.02072]
8
[-0.47396064 -2.8818233  -2.4542987   0.39455837]
[125.953636 134.52357  124.16205  123.69429 ]
9
[-0.49626052 -3.204234   -2.8536959   0.50341153]
[157.77419 168.6043  156.3724  156.20341]
10
[-0.51484567 -3.5127776  -3.2501707   0.62265706]
[195.13